version: '3.5'

services:
    app_service:
        image: path/to/registry/app_service:master
        ports:
            - 80:80

    server_service:
        image: path/to/registry/server_service:master
        command: node server.js
        ports:
            - 3001:3001
        depends_on:
            - redis_service

    redis_service:
        image: redis:5.0.5-alpine
        ports:
            - 6379:6379
